import type { BizPaymentCase } from './types'

export const bizPaymentCases: BizPaymentCase[] = [
  {
    id: 'BP-001',
    priority: 'P0',
    title: '打开 UpgradeModal 基础信息渲染',
    requirementId: 'BP-REQ-01',
    preconditions: ['已登录 Dashboard 且可访问 Business 页面'],
    steps: ['点击 Upgrade 或 Extend 按钮'],
    assertions: [
      '出现支付弹窗',
      '可见 Subscription Type / Payment Amount / Payment Method / You pay / Confirm',
    ],
  },
  {
    id: 'BP-002',
    priority: 'P0',
    title: 'Activation Date 必填（非 grace period）',
    requirementId: 'BP-REQ-01',
    preconditions: ['当前 space 非 inGracePeriod'],
    steps: ['不选择 Activation Date，直接尝试点击 Confirm'],
    assertions: ['Confirm 为 disabled'],
  },
  {
    id: 'BP-003',
    priority: 'P0',
    title: '仅 Wallet 且余额充足可提交',
    requirementId: 'BP-REQ-02',
    preconditions: ['钱包余额覆盖支付金额'],
    steps: ['选择 From Wallet', '选择支持的链和币种'],
    assertions: ['You pay 显示金额拆解', 'Confirm 可点击'],
  },
  {
    id: 'BP-004',
    priority: 'P0',
    title: '仅 Wallet 余额不足拦截',
    requirementId: 'BP-REQ-02',
    preconditions: ['钱包余额不足'],
    steps: ['选择 From Wallet 并选择币种'],
    assertions: ['显示 Insufficient Balance', 'Confirm 为 disabled'],
  },
  {
    id: 'BP-005',
    priority: 'P0',
    title: 'Gas Station 余额为 0 时禁用',
    requirementId: 'BP-REQ-03',
    preconditions: ['SpaceBalance 为 0'],
    steps: ['打开支付弹窗'],
    assertions: ['From Gas Station 选项禁用'],
  },
  {
    id: 'BP-006',
    priority: 'P0',
    title: '仅 Gas Station 且余额不足拦截',
    requirementId: 'BP-REQ-03',
    preconditions: ['0 < Gas Station 余额 < 支付金额'],
    steps: ['只选择 From Gas Station'],
    assertions: [
      '显示不足提示: Insufficient Gas Station balance',
      'Confirm 为 disabled',
    ],
  },
  {
    id: 'BP-007',
    priority: 'P0',
    title: '组合支付金额拆分显示',
    requirementId: 'BP-REQ-04',
    preconditions: ['Gas Station 与 Wallet 合计可覆盖支付金额'],
    steps: ['同时选择 Wallet 与 Gas Station'],
    assertions: ['You pay breakdown 显示 Wallet 金额与 Gas Station 金额'],
  },
  {
    id: 'BP-008',
    priority: 'P0',
    title: 'Service Agreement 未勾选拦截',
    requirementId: 'BP-REQ-05',
    preconditions: ['支付方式和金额前置均满足'],
    steps: ['不勾选 Service Agreement 直接点击 Confirm'],
    assertions: ['Confirm 为 disabled'],
  },
  {
    id: 'BP-009',
    priority: 'P0',
    title: 'registerSpacePaymentTask success=false 错误提示',
    requirementId: 'BP-REQ-06',
    preconditions: ['mock mutation 返回 success=false 与 failureReason'],
    steps: ['点击 Confirm'],
    assertions: ['显示 failureReason', '不进入链上交互和轮询'],
  },
  {
    id: 'BP-010',
    priority: 'P0',
    title: '纯 Gas Station 支付轮询成功',
    requirementId: 'BP-REQ-06',
    preconditions: ['mutation 返回 newPaymentMethodPaymentData=null'],
    steps: ['点击 Confirm 后开始轮询支付状态'],
    assertions: ['进入 Processing', '状态 Success 后显示成功结果'],
  },
  {
    id: 'BP-011',
    priority: 'P0',
    title: 'Wallet/组合支付三步状态流转',
    requirementId: 'BP-REQ-08',
    preconditions: ['mutation 返回 newPaymentMethodPaymentData'],
    steps: ['提交支付并在钱包确认'],
    assertions: [
      '依次显示 Waiting for Confirmation -> Processing Payment -> Success',
    ],
  },
  {
    id: 'BP-012',
    priority: 'P0',
    title: '轮询失败终态展示失败弹窗',
    requirementId: 'BP-REQ-09',
    preconditions: ['spacePaymentTaskInfo 最终返回 Failed'],
    steps: ['发起支付并等待轮询'],
    assertions: ['停止轮询', '显示 PayFailModal'],
  },
  {
    id: 'BP-013',
    priority: 'P1',
    title: 'Allowance 足够时跳过 approve',
    requirementId: 'BP-REQ-07',
    preconditions: ['allowance >= tokenAmount'],
    steps: ['发起 Wallet 支付'],
    assertions: ['直接调用 pay()', '不发送 approve 交易'],
    envDependent: true,
  },
  {
    id: 'BP-014',
    priority: 'P1',
    title: 'Allowance 不足先 approve 后 pay',
    requirementId: 'BP-REQ-07',
    preconditions: ['allowance < tokenAmount'],
    steps: ['发起 Wallet 支付'],
    assertions: ['先 approve', 'approve 成功后 pay'],
    envDependent: true,
  },
  {
    id: 'BP-015',
    priority: 'P1',
    title: 'Ethereum USDT 走 approve(0)->approve(amount)',
    requirementId: 'BP-REQ-07',
    preconditions: ['链=Ethereum', 'token=USDT', '0<allowance<amount'],
    steps: ['发起 Wallet 支付'],
    assertions: ['依次调用 approve(0) 和 approve(amount)', '随后调用 pay'],
    envDependent: true,
  },
  {
    id: 'BP-016',
    priority: 'P1',
    title: 'Gravity G 原生币支付路径',
    requirementId: 'BP-REQ-07',
    preconditions: ['链=Gravity', 'token=G'],
    steps: ['发起 Wallet 支付'],
    assertions: ['跳过 allowance/approve', 'pay() 使用 value=amount'],
    envDependent: true,
  },
  {
    id: 'BP-017',
    priority: 'P1',
    title: '钱包链不一致时自动切链',
    requirementId: 'BP-REQ-14',
    preconditions: ['钱包当前链与支付链不一致'],
    steps: ['发起 Wallet 支付'],
    assertions: ['先执行 switchChain', '后续继续 approve/pay 流程'],
    envDependent: true,
  },
  {
    id: 'BP-018',
    priority: 'P1',
    title: '用户拒签/交易失败后取消任务',
    requirementId: 'BP-REQ-07',
    preconditions: ['mock approve 或 pay 失败'],
    steps: ['提交支付并在钱包拒签/模拟链上失败'],
    assertions: ['提示 Payment Failed', '调用 cancelSpacePaymentTask'],
    envDependent: true,
  },
  {
    id: 'BP-019',
    priority: 'P1',
    title: 'Billing Payment Method 映射显示',
    requirementId: 'BP-REQ-10',
    preconditions: ['历史数据包含 3 种 paymentMethod'],
    steps: ['进入 Settings -> Billing'],
    assertions: [
      'GasStation 显示 Gas Station',
      'Token 显示 Wallet',
      'GasStationAndToken 显示 Gas Station & Wallet',
    ],
  },
  {
    id: 'BP-020',
    priority: 'P1',
    title: 'Billing TXID 展示与跳转',
    requirementId: 'BP-REQ-10',
    preconditions: ['历史数据中包含 txid 字段或 tx 字段'],
    steps: ['进入 Settings -> Billing 并查看历史卡片'],
    assertions: ['TXID 显示短链', '点击跳转浏览器', '空值显示 --'],
  },
  {
    id: 'BP-021',
    priority: 'P1',
    title: 'Gas Station History 改名检查',
    requirementId: 'BP-REQ-11',
    preconditions: ['可访问 Gas Station History'],
    steps: ['进入 Gas Station -> History'],
    assertions: ['存在 Deposit History 标签', '列表 Type 列值为 Deposit'],
  },
  {
    id: 'BP-022',
    priority: 'P1',
    title: 'Expense Statement Type 列检查',
    requirementId: 'BP-REQ-12',
    preconditions: ['可访问 Expense Statement 且有数据'],
    steps: ['切换到 Expense Statement'],
    assertions: [
      '存在 Type 列',
      '可见 Quest Subsidy 或 Business+ Subscription',
    ],
  },
  {
    id: 'BP-023',
    priority: 'P1',
    title: 'Business+ Subscription 行占位规则',
    requirementId: 'BP-REQ-12',
    preconditions: ['Expense 列表含 Business+ Subscription 行'],
    steps: ['定位 Business+ Subscription 行'],
    assertions: ['Claims/Avg Gas Price/Avg Claim Cost 显示 -'],
  },
  {
    id: 'BP-024',
    priority: 'P1',
    title: '组合支付 Gas Station 足额时 Wallet=0',
    requirementId: 'BP-REQ-04',
    preconditions: ['Gas Station 余额 >= 支付金额'],
    steps: ['勾选 Wallet + Gas Station'],
    assertions: ['You pay 中 Wallet 金额为 0 或不再需要钱包支付'],
  },
  {
    id: 'BP-025',
    priority: 'P2',
    title: 'Daimo Pay 跳转流程不可达',
    requirementId: 'BP-REQ-13',
    preconditions: ['进入 UpgradeModal'],
    steps: ['提交支付流程前后观察页面行为'],
    assertions: ['不再出现 paymentUrl 跳转到第三方支付页'],
  },
  {
    id: 'BP-026',
    priority: 'P2',
    title: 'Daimo Pay 文案清理回归',
    requirementId: 'BP-REQ-13',
    preconditions: ['覆盖 Business / Billing 用户主路径'],
    steps: ['检查页面可见文案'],
    assertions: ['关键路径不出现 Daimo Pay 文案'],
  },
  {
    id: 'BP-027',
    priority: 'P2',
    title: 'Activation Date tooltip 文案检查',
    requirementId: 'BP-REQ-01',
    preconditions: ['升级弹窗可见 Activation Date 区域'],
    steps: ['hover 信息图标'],
    assertions: ['展示「Your subscription will start...」提示文案'],
  },
  {
    id: 'BP-028',
    priority: 'P2',
    title: '余额不足文案区分检查',
    requirementId: 'BP-REQ-02',
    preconditions: ['可构造 Wallet 不足和 Gas Station 不足两种数据'],
    steps: ['分别触发两类不足场景'],
    assertions: [
      'Wallet 显示 Insufficient Balance',
      'Gas Station 显示专属不足文案',
    ],
  },
  {
    id: 'BP-029',
    priority: 'P2',
    title: '处理中防误操作提示检查',
    requirementId: 'BP-REQ-08',
    preconditions: ['进入 PayProcessModal'],
    steps: ['查看 confirming 和 processing 两个步骤副标题'],
    assertions: ['提示中包含请勿刷新/关闭页面信息'],
  },
  {
    id: 'BP-030',
    priority: 'P2',
    title: '支付成功后业务数据刷新',
    requirementId: 'BP-REQ-09',
    preconditions: ['支付流程成功'],
    steps: ['观察 Business 页面和 Billing 页面状态'],
    assertions: ['订阅状态更新', '历史记录新增当前支付项'],
  },
]
